import Ingredient from '../../types/Recipe.d';
const IngredientsList = [
    {value: 'Bread', label: 'Bread'},
    {value: 'Butter', label: 'Butter'},
    {value: 'Cheese', label: 'Cheese'},
    {value: 'Chicken', label: 'Chicken'},
    {value: 'Eggs', label: 'Eggs'},
    {value: 'Flour', label: 'Flour'},
    {value: 'Milk', label: 'Milk'},
    {value: 'Olive Oil', label: 'Olive Oil'},
    {value: 'Onion', label: 'Onion'},
    {value: 'Paprika', label: 'Paprika'},
    {value: 'Pepper', label: 'Pepper'},
    {value: 'Salt', label: 'Salt'},
    {value: 'Sugar', label: 'Sugar'},
    {value: 'Tomato', label: 'Tomato'},
    {value: 'Water', label: 'Water'},
    {value: 'Yeast', label: 'Yeast'},
    {value: 'Zucchini', label: 'Zucchini'},
    {value: 'Almond', label: 'Almond'},
    {value: 'Apple', label: 'Apple'},
    {value: 'Apricot', label: 'Apricot'},
    {value: 'Asparagus', label: 'Asparagus'},
    {value: 'Avocado', label: 'Avocado'},
    {value: 'Banana', label: 'Banana'},
    {value: 'Basil', label: 'Basil'},
    {value: 'Bean', label: 'Bean'},
    {value: 'Beet', label: 'Beet'},
];

export default IngredientsList;