const Ingredients = [
    { id: 1, value: 'bread'},
    { id: 2, value: 'milk'},
    { id: 3, value: 'eggs'},
    { id: 4, value: 'sugar'},
    { id: 5, value: 'salt'},
    { id: 6, value: 'pepper'},
    { id: 7, value: 'oil'},
    { id: 8, value: 'butter'},
    { id: 9, value: 'cheese'},
    { id: 10, value: 'onion'},
    { id: 11, value: 'tomato'},
    { id: 12, value: 'carrot'},
    { id: 13, value: 'cucumber'},
    { id: 14, value: 'potato'},
    { id: 15, value: 'chicken'},
    { id: 16, value: 'beef'},
    { id: 17, value: 'pork'},
    { id: 18, value: 'lamb'},
    { id: 19, value: 'fish'},
    { id: 20, value: 'mutton'},
    { id: 21, value: 'prawns'},
    { id: 22, value: 'crab'},
    { id: 23, value: 'oyster'},
    { id: 24, value: 'squid'},
    { id: 25, value: 'shrimp'},
    { id: 26, value: 'scallop'},
    { id: 27, value: 'prawn'},
];

export default Ingredients;