"""Revoke Token

Revision ID: 5df1e767d177
Revises: 95b7f6851101
Create Date: 2022-06-24 03:41:26.721180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5df1e767d177'
down_revision = '95b7f6851101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_token_jti'), 'revoked_token', ['jti'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revoked_token_jti'), table_name='revoked_token')
    op.drop_table('revoked_token')
    # ### end Alembic commands ###
